// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "fmt"

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const BigqueryDatapolicyDataPolicyIAMAssetType string = "bigquerydatapolicy.googleapis.com/DataPolicy"

func resourceConverterBigqueryDatapolicyDataPolicyIamPolicy() ResourceConverter {
	return ResourceConverter{
		AssetType:         BigqueryDatapolicyDataPolicyIAMAssetType,
		Convert:           GetBigqueryDatapolicyDataPolicyIamPolicyCaiObject,
		MergeCreateUpdate: MergeBigqueryDatapolicyDataPolicyIamPolicy,
	}
}

func resourceConverterBigqueryDatapolicyDataPolicyIamBinding() ResourceConverter {
	return ResourceConverter{
		AssetType:         BigqueryDatapolicyDataPolicyIAMAssetType,
		Convert:           GetBigqueryDatapolicyDataPolicyIamBindingCaiObject,
		FetchFullResource: FetchBigqueryDatapolicyDataPolicyIamPolicy,
		MergeCreateUpdate: MergeBigqueryDatapolicyDataPolicyIamBinding,
		MergeDelete:       MergeBigqueryDatapolicyDataPolicyIamBindingDelete,
	}
}

func resourceConverterBigqueryDatapolicyDataPolicyIamMember() ResourceConverter {
	return ResourceConverter{
		AssetType:         BigqueryDatapolicyDataPolicyIAMAssetType,
		Convert:           GetBigqueryDatapolicyDataPolicyIamMemberCaiObject,
		FetchFullResource: FetchBigqueryDatapolicyDataPolicyIamPolicy,
		MergeCreateUpdate: MergeBigqueryDatapolicyDataPolicyIamMember,
		MergeDelete:       MergeBigqueryDatapolicyDataPolicyIamMemberDelete,
	}
}

func GetBigqueryDatapolicyDataPolicyIamPolicyCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBigqueryDatapolicyDataPolicyIamAsset(d, config, expandIamPolicyBindings)
}

func GetBigqueryDatapolicyDataPolicyIamBindingCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBigqueryDatapolicyDataPolicyIamAsset(d, config, expandIamRoleBindings)
}

func GetBigqueryDatapolicyDataPolicyIamMemberCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBigqueryDatapolicyDataPolicyIamAsset(d, config, expandIamMemberBindings)
}

func MergeBigqueryDatapolicyDataPolicyIamPolicy(existing, incoming Asset) Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeBigqueryDatapolicyDataPolicyIamBinding(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAuthoritativeBindings)
}

func MergeBigqueryDatapolicyDataPolicyIamBindingDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAuthoritativeBindings)
}

func MergeBigqueryDatapolicyDataPolicyIamMember(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAdditiveBindings)
}

func MergeBigqueryDatapolicyDataPolicyIamMemberDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAdditiveBindings)
}

func newBigqueryDatapolicyDataPolicyIamAsset(
	d TerraformResourceData,
	config *Config,
	expandBindings func(d TerraformResourceData) ([]IAMBinding, error),
) ([]Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := assetName(d, config, "//bigquerydatapolicy.googleapis.com/projects/{{project}}/locations/{{location}}/dataPolicies/{{data_policy_id}}")
	if err != nil {
		return []Asset{}, err
	}

	return []Asset{{
		Name: name,
		Type: BigqueryDatapolicyDataPolicyIAMAssetType,
		IAMPolicy: &IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchBigqueryDatapolicyDataPolicyIamPolicy(d TerraformResourceData, config *Config) (Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("location"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}
	if _, ok := d.GetOk("data_policy_id"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}

	return fetchIamPolicy(
		BigqueryDatapolicyDataPolicyIamUpdaterProducer,
		d,
		config,
		"//bigquerydatapolicy.googleapis.com/projects/{{project}}/locations/{{location}}/dataPolicies/{{data_policy_id}}",
		BigqueryDatapolicyDataPolicyIAMAssetType,
	)
}
