// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "fmt"

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const ComputeRegionDiskIAMAssetType string = "compute.googleapis.com/RegionDisk"

func resourceConverterComputeRegionDiskIamPolicy() ResourceConverter {
	return ResourceConverter{
		AssetType:         ComputeRegionDiskIAMAssetType,
		Convert:           GetComputeRegionDiskIamPolicyCaiObject,
		MergeCreateUpdate: MergeComputeRegionDiskIamPolicy,
	}
}

func resourceConverterComputeRegionDiskIamBinding() ResourceConverter {
	return ResourceConverter{
		AssetType:         ComputeRegionDiskIAMAssetType,
		Convert:           GetComputeRegionDiskIamBindingCaiObject,
		FetchFullResource: FetchComputeRegionDiskIamPolicy,
		MergeCreateUpdate: MergeComputeRegionDiskIamBinding,
		MergeDelete:       MergeComputeRegionDiskIamBindingDelete,
	}
}

func resourceConverterComputeRegionDiskIamMember() ResourceConverter {
	return ResourceConverter{
		AssetType:         ComputeRegionDiskIAMAssetType,
		Convert:           GetComputeRegionDiskIamMemberCaiObject,
		FetchFullResource: FetchComputeRegionDiskIamPolicy,
		MergeCreateUpdate: MergeComputeRegionDiskIamMember,
		MergeDelete:       MergeComputeRegionDiskIamMemberDelete,
	}
}

func GetComputeRegionDiskIamPolicyCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newComputeRegionDiskIamAsset(d, config, expandIamPolicyBindings)
}

func GetComputeRegionDiskIamBindingCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newComputeRegionDiskIamAsset(d, config, expandIamRoleBindings)
}

func GetComputeRegionDiskIamMemberCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newComputeRegionDiskIamAsset(d, config, expandIamMemberBindings)
}

func MergeComputeRegionDiskIamPolicy(existing, incoming Asset) Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeComputeRegionDiskIamBinding(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAuthoritativeBindings)
}

func MergeComputeRegionDiskIamBindingDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAuthoritativeBindings)
}

func MergeComputeRegionDiskIamMember(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAdditiveBindings)
}

func MergeComputeRegionDiskIamMemberDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAdditiveBindings)
}

func newComputeRegionDiskIamAsset(
	d TerraformResourceData,
	config *Config,
	expandBindings func(d TerraformResourceData) ([]IAMBinding, error),
) ([]Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := assetName(d, config, "//compute.googleapis.com/projects/{{project}}/regions/{{region}}/disks/{{name}}")
	if err != nil {
		return []Asset{}, err
	}

	return []Asset{{
		Name: name,
		Type: ComputeRegionDiskIAMAssetType,
		IAMPolicy: &IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchComputeRegionDiskIamPolicy(d TerraformResourceData, config *Config) (Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("{{region}}"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}
	if _, ok := d.GetOk("{{name}}"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}

	return fetchIamPolicy(
		ComputeRegionDiskIamUpdaterProducer,
		d,
		config,
		"//compute.googleapis.com/projects/{{project}}/regions/{{region}}/disks/{{name}}",
		ComputeRegionDiskIAMAssetType,
	)
}
