// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "fmt"

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const IapTunnelIAMAssetType string = "iap.googleapis.com/Tunnel"

func resourceConverterIapTunnelIamPolicy() ResourceConverter {
	return ResourceConverter{
		AssetType:         IapTunnelIAMAssetType,
		Convert:           GetIapTunnelIamPolicyCaiObject,
		MergeCreateUpdate: MergeIapTunnelIamPolicy,
	}
}

func resourceConverterIapTunnelIamBinding() ResourceConverter {
	return ResourceConverter{
		AssetType:         IapTunnelIAMAssetType,
		Convert:           GetIapTunnelIamBindingCaiObject,
		FetchFullResource: FetchIapTunnelIamPolicy,
		MergeCreateUpdate: MergeIapTunnelIamBinding,
		MergeDelete:       MergeIapTunnelIamBindingDelete,
	}
}

func resourceConverterIapTunnelIamMember() ResourceConverter {
	return ResourceConverter{
		AssetType:         IapTunnelIAMAssetType,
		Convert:           GetIapTunnelIamMemberCaiObject,
		FetchFullResource: FetchIapTunnelIamPolicy,
		MergeCreateUpdate: MergeIapTunnelIamMember,
		MergeDelete:       MergeIapTunnelIamMemberDelete,
	}
}

func GetIapTunnelIamPolicyCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newIapTunnelIamAsset(d, config, expandIamPolicyBindings)
}

func GetIapTunnelIamBindingCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newIapTunnelIamAsset(d, config, expandIamRoleBindings)
}

func GetIapTunnelIamMemberCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newIapTunnelIamAsset(d, config, expandIamMemberBindings)
}

func MergeIapTunnelIamPolicy(existing, incoming Asset) Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeIapTunnelIamBinding(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAuthoritativeBindings)
}

func MergeIapTunnelIamBindingDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAuthoritativeBindings)
}

func MergeIapTunnelIamMember(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAdditiveBindings)
}

func MergeIapTunnelIamMemberDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAdditiveBindings)
}

func newIapTunnelIamAsset(
	d TerraformResourceData,
	config *Config,
	expandBindings func(d TerraformResourceData) ([]IAMBinding, error),
) ([]Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := assetName(d, config, "//iap.googleapis.com/{{tunnel}}")
	if err != nil {
		return []Asset{}, err
	}

	return []Asset{{
		Name: name,
		Type: IapTunnelIAMAssetType,
		IAMPolicy: &IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchIapTunnelIamPolicy(d TerraformResourceData, config *Config) (Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("{{tunnel}}"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}

	return fetchIamPolicy(
		IapTunnelIamUpdaterProducer,
		d,
		config,
		"//iap.googleapis.com/{{tunnel}}",
		IapTunnelIAMAssetType,
	)
}
