# See config-validator project

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/terraform-validator', '.' ]
images:
  - gcr.io/$PROJECT_ID/terraform-validator
timeout: 1200s # 20 minutes