# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See cloud-foundation-cicd project

timeout: 1800s
steps:
- id: build
  name: 'gcr.io/cloud-builders/go:1.15'
  entrypoint: /usr/bin/make
  args: ['build']
- id: test-go-licenses
  name: 'gcr.io/cloud-builders/go:1.15'
  entrypoint: /usr/bin/make
  env:
    - 'GO111MODULE=on'
  args: ['test-go-licenses']
  waitFor: ['build']
- id: test
  name: 'gcr.io/cloud-builders/go:1.15'
  entrypoint: /usr/bin/make
  args: ['test']
  env:
    - 'TEST_PROJECT=$_TEST_PROJECT'
    - 'GOPATH=/gopath'
  waitFor: ['test-go-licenses']
tags:
- 'ci'
options:
  machineType: 'N1_HIGHCPU_8'
